### ISSUE TITLE
Pipeline Resource ManagementGroups Input Must be Valid.

### ISSUE THREAD

**Issue by autocloudarc** [Azure/CanadaPubSecALZ#174]
**Describe the bug**
Error when running roles-ci pipline.

**To Reproduce**
1. Run the roles-ci pipeline after configuring according to instructions at: https://github.com/Azure/CanadaPubSecALZ/blob/main/docs/onboarding/azure-devops-pipelines.md Step 4.

**Expected behavior**
Roles are applied to management groups

**Screenshots**
![Pipeline-Resource-ManagementGroups-InputMustBeValid](https://user-images.githubusercontent.com/15109536/155053348-04532e29-6915-4c37-8bee-8bf6620689f3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Version 98.0.1108.56 (Official build) (64-bit)

**Additional context**
Add any other context about the problem here

**Comment by SenthuranSivananthan** [comment]
@autocloudarc, this is because of line 25.  Can you ensure that the ADO pipeline for management groups is named "management-groups-ci".  From #173, looks like you are missing an "s" after group.  Can you try this out and let me know?

This was added so that we ensure MG pipeline is executed before running the roles ADO pipeline.

**Comment by autocloudarc** [comment]
@SenthuranSivananthan. Yes! That was it. I misspelled "management-groups-ci". I just tested it and it works great now. Thank you! :-)
