### ISSUE TITLE
Refactor pipelines to leverage CARML

### ISSUE THREAD

**Issue by skeeler** [Azure/CanadaPubSecALZ#195]
**Is your feature request related to a problem? Please describe.**
Refactor existing pipeline YAML to use the [Common Azure Resource Modules Library](https://github.com/Azure/ResourceModules), promoting code reuse and reducing maintenance overhead of managing ARM/Bicep modules for changes.

**Describe the solution you'd like**
Leverage Azure Pipelines [Check out multiple repositories in your pipeline](https://docs.microsoft.com/azure/devops/pipelines/repos/multi-repo-checkout) capability to reference the CARML modules rather than maintaining the existing [.azresources](https://github.com/Azure/CanadaPubSecALZ/tree/main/azresources) source.

**Describe alternatives you've considered**
Leave existing `.azresources` code in place and continue using as-is.

**Comment by SenthuranSivananthan** [comment]
This work should depend on Bicep Public Repository with CARML available as versioned resources to pin our implementation.  Otherwise we risk any upstream breaking changes into this project.

**Comment by SenthuranSivananthan** [comment]
There are a number of features we need enabled in CARML for us to swap our implementation.  These include:

* Support for Public Bicep Registry - https://github.com/Azure/ResourceModules/issues/1169
* Support for Customer Managed Keys - _Created 1 GH issue related to Storage Account but will be across the board since CMK is now an audit policy in NIST 800-53 Rev 4._ - https://github.com/Azure/ResourceModules/issues/1209.  We support CMK   in many resources.
* Bug fixes such as SQL Vulnerability Assessment with Storage Account + Private Endpoints - https://github.com/Azure/ResourceModules/issues/1210

These are sample blockers before transitioning to CARML as the base Resource Modules.

**Comment by SenthuranSivananthan** [comment]
Closing this issue.  We will wait for resources to be available as [Bicep Registry Modules](https://github.com/Azure/bicep-registry-modules) to adopt.
