### ISSUE TITLE
Azure Pipline CI jobs fail where var-managementgroup-hierarchy is not set 

### ISSUE THREAD

**Issue by wanpeng-cds** [Azure/CanadaPubSecALZ#210]
**Describe the bug**
With the new v0.9.0 update, the deployment failed in Azure pipline.  

We have `var-parentManagementGroupId` and `var-topLevelManagementGroupName` set but **no** `var-managementgroup-hierarchy` in the config file. 

However the CI jobs failed at the `Load Variables` step:
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/97911035/157902251-886ae38b-3a4d-46ba-abcc-dbe3f249e4fa.png">

**To Reproduce**
1. set `var-parentManagementGroupId` and `var-topLevelManagementGroupName` in `config/variables/orgname-main.yml`
2. do NOT set `var-managementgroup-hierarchy` in the same file
3. run Azure pipline jobs 

**Expected behavior**
Azure pipline jobs run without errors

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 99.0.4844.51 (Official Build) (x86_64)

**Comment by SenthuranSivananthan** [comment]
I'm able to reproduce the problem.  It's because when a pipeline variable is not defined, ADO will place the variable name as the value instead of `blank`.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#runtime-expression-syntax
![image](https://user-images.githubusercontent.com/16688027/157910683-223b58d0-cbb5-4ce1-976d-06f9c0740c9a.png)

Thanks for raising the bug.

**Comment by wanpeng-cds** [comment]
Thanks @SenthuranSivananthan !

**Comment by SenthuranSivananthan** [comment]
I'm working on testing a fix.  In the meantime, you can workaround the bug by adding the new variable `var-managementgroup-hierarchy` to your config with no value.  For example:

```yaml
  var-parentManagementGroupId: 343ddfdb-bef5-46d9-99cf-ed67d5948783
  var-topLevelManagementGroupName: pubsec
  var-managementgroup-hierarchy:
```
