### ISSUE TITLE
RFC 6598

### ISSUE THREAD

**Issue by davidmonk-cbts** [Azure/CanadaPubSecALZ#391]
Is there a way to have a deployment of this configuration without any utilization of the 6598 space? At this time, a customer we have will have this Azure deployment with no inter-department or external connections at all.

**Comment by SenthuranSivananthan** [comment]
You can deploy without the 6598 address space.  The VNET address spaces are array input (in the parameters.json file), therefore you can just add RFC 1918 spaces.

**Comment by dmonkcbts** [comment]
We tried that. The problem came in with the identity deployment also requiring that item. It appears to be required by the schema.


David Monk

Cloud Architect – Cloud Engineering

________________________________

**Comment by tredell** [comment]
@dmonkcbts is the identity deployment failing on the UDR configuration? 

If yes, we can try splitting out  'SpokeUdrHubRFC6598FWRoute' config (lines 208-216 in the Identity networking bicep file) and making it a conditional union based on if the variable is blank "" or has an IP range in it.

**Comment by dmonkcbts** [comment]
I believe so. I am not the one deploying this. I only configured the network portion as the customer wanted to use Palo Alto firewalls instead of Azure or Fortigate. I had to make some extensive changes myself to accommodate their design, with no inter-department or public access. Therefore, there is no need for 6598. Those managing the identity deployment just told me it required 6598 space.


David Monk

Cloud Architect – Cloud Engineering

________________________________

**Comment by alenat10** [comment]
As far as I recall the parameter is set as required in line 137 in schema for  Identity archetype.
